version: 2

build:
  image: latest

python:
  version: "3.8"
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
        - all
      

sphinx:
  fail_on_warning: false

formats: []
