jobs:
  test:
    docker:
      - image: circleci/python:3.8
      - image: circleci/postgres:11.5-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres_pw
          POSTGRES_DB: test
    environment:
      DB_NAME: test
      DB_USER: postgres
      DB_PASSWORD: postgres_pw
      DB_HOST: localhost
    steps:
      - checkout
      - run: pip install --no-cache-dir poetry psycopg2-binary
      - run: poetry install
      - run: poetry run black --diff --check .
      - run: poetry run flake8 .
      - run: poetry run isort --check-only --recursive --diff .
      - run: poetry run tests

  build:
    executor: python/default
    steps:
      - checkout
      - run: sed -i 's/version = "0.1.1"/version = "'$CIRCLE_TAG'"/g' pyproject.toml
      - python/install-packages:
          pkg-manager: poetry
      - run: poetry build
      - run: poetry config pypi-token.pypi $PYPI_TOKEN
      - run: poetry publish
orbs:
  python: circleci/python@1.0.0
version: 2.1
workflows:
  main:
    jobs:
      - test
      - build:
          requires:
            - test
          filters:
            branches:
              ignore: /^.*/
            tags:
              only: /^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$/